{% set version = "14.0.6" %}

package:
  name: clang-win-activation
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

outputs:
  - name: clang_win-64
    script: install-pkg.bat  # [win]
    skip: True  # [not win]
    build:
      run_exports:
        strong:
          - vc >=14.1
          - vs2015_runtime >={{ MSVC_HEADERS_VERSION }}
    requirements:
      build:
        - m2-sed  # [win]
      host:
        # Needed to create the symlinks
        - clangxx     {{ version }}
        - llvm-tools  {{ version }}
      run:
        - vs2017_win-64 19.16.27032                                   # [win]
        - vswhere                                                     # [win]
        - clangxx             {{ version }}
        - llvm-tools          {{ version }}
        - lld                 {{ version }}
        - compiler-rt         {{ version }}
        - compiler-rt_win-64  {{ version }}
    test:                     # [win]
      files:                  # [win]
        - test.c              # [win]
        - test.cpp            # [win]
        - run_test_clang.bat  # [win]
      commands:               # |win]
        - run_test_clang.bat  # [win]

about:
  home: https://github.com/conda-forge/clang-win-activation-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'clang (cross) compiler for windows with MSVC ABI compatbility'
  description: |
    To use this package in a normal conda environment, do the following

       export CONDA_BUILD_WINSDK=/opt

    To use this package in a conda-build environment, add the following

       CONDA_BUILD_WINSDK:
         - "/opt"

    in $HOME/conda_build_config.yaml and use `clang_win-64` as the compiler.

    By setting this variable, you are agreeing to the terms and conditions
    of the Windows SDK and the MSVC headers. If the Windows SDK and MSVC
    headers are not inside CONDA_BUILD_WINSDK, they would be automatically
    downloaded.
  doc_url: https://github.com/conda-forge/clang-win-activation-feedstock
  dev_url: https://github.com/conda-forge/clang-win-activation-feedstock

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
    - katietz

