{% set version = "19.1.7" %}

{% if not vsyear %}
  {% set vsyear = "" %}
  {% set runtime_version = "14.40.33810" %}
  {% set cl_version = "19.40" %}
  {% set vcver = "" %}
{% endif %}

{% set vc_major = vcver.split(".")[0] %}

package:
  name: clang-win-activation
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

outputs:
  - name: clang_win-64
    script: install-pkg.bat
    skip: True  # [not win]
    run_exports:
        strong:
          #  See: https://github.com/AnacondaRecipes/vc-feedstock/blob/main/recipe/meta.yaml
          - vc >={{ vcver }},<{{ vc_major | int + 1 }}
          - vc{{ vc_major }}_runtime >={{ runtime_version }}
          # Need ucrt for windows<10 and when the VC runtime does not bundle it
          - ucrt >=10.0.20348.0  # [(vsver >=16) and (cross_target_platform == "win-64" or cross_target_platform == "win-32")]
    requirements:
      build:
        - msys2-sed
      host:
        # Needed to create the symlinks
        - clangxx     {{ version }}
        - llvm-tools  {{ version }}
      run:
        - vs_{{ target_platform }} {{ vsyear }}
        - clangxx             {{ version }}
        - llvm-tools          {{ version }}
        - lld                 {{ version }}
        - compiler-rt         {{ version }}
        - compiler-rt_win-64  {{ version }}
    test:                   
      files:                
        - test.c            
        - test.cpp          
        - run_test_clang.bat
      commands:             
        - run_test_clang.bat

about:
  home: https://github.com/conda-forge/clang-win-activation-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'clang (cross) compiler for windows with MSVC ABI compatbility'
  description: |
    To use this package in a normal conda environment, do the following

       export CONDA_BUILD_WINSDK=/opt

    To use this package in a conda-build environment, add the following

       CONDA_BUILD_WINSDK:
         - "/opt"

    in $HOME/conda_build_config.yaml and use `clang_win-64` as the compiler.

    By setting this variable, you are agreeing to the terms and conditions
    of the Windows SDK and the MSVC headers. If the Windows SDK and MSVC
    headers are not inside CONDA_BUILD_WINSDK, they would be automatically
    downloaded.
  doc_url: https://github.com/conda-forge/clang-win-activation-feedstock
  dev_url: https://github.com/conda-forge/clang-win-activation-feedstock

extra:
  skip-lints:
    - stdlib_must_be_in_build
  recipe-maintainers:
    - isuruf
    - xhochy
    - katietz

